import "./globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Provider from "./_trpc/provider";
import { ThemeProvider } from "@/components/ThemeProvider";

const quicksand = Quicksand({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Provider>{children}</Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
